### ISSUE TITLE
Ordering associations

### ISSUE THREAD

**Issue by Frexuz** [contentful/contentful_model#34]
Would it be possible somehow to order a models children? Maybe something similar to:
`Faq.all.order(:name, 'questions.name').load`

```
class Faq < ContentfulModel::Base
  self.content_type_id = 'category'
  has_many :questions
end
```

or would I have to do it on the array? `faq.questions.sort_by(&:name).each`

**Comment by dlitvakb** [comment]
Hey @Frexuz,

Currently the only way of fetching them in a sorted manner is by doing it on the array.

It could be a good idea to add more options in the future for allowing the related resources to be already sorted and maybe add filtering as well.

Currently that involves a lot of work and is a very low priority. But since you are already asking for it, it's definitely worth consideration.

Thanks for the submission

Cheers

**Comment by Frexuz** [comment]
I thought so :)

**Comment by dlitvakb** [comment]
Hey @Frexuz,

Adding sorting and filtering options has been added to our backlog, we'll be tackling this issue in the few months to come.

I'll mark this as closed.

Cheers
