### ISSUE TITLE
Associations returning instances of the wrong class

### ISSUE THREAD

**Issue by georgebrock** [contentful/contentful_model#53]
## The setup

I've tested this against contentful_model v 0.1.7.1 and against master (a747f541541510a470c6f8741e20890b79a52380 at the time of writing).

I have two models:

```ruby
class Requirement < ContentfulModel::Base
  self.content_type_id = "requirement"
  has_one :category
end

class Category < ContentfulModel::Base
  self.content_type_id = "category"
  belongs_to_many :requirements
end
```

## The problem

When I try to get a `Requirement`'s `Category`, the returned object is a `Contentful::Entry` (in v0.1.7.1) or a `Contentful::DynamicEntry` (in master) instead of a `Category`:

```
[1] pry(main)> Requirement.first.category.class
=> Contentful::Entry
```

Under 0.1.7.1, I can't get to the attributes of the returned category without going via `#fields`. Under master, I can get the attributes, but I still can't get to any of the methods I've defined on my `Category` class.

This behaviour continues until I call `Category.load` for any reason, after which it changes to the expected behaviour and returns `Category` instances:

```
[2] pry(main)> Category.load
=> [#<Category: …>, …]
[3] pry(main)> Requirement.first.category.class
=> Category
```

## The work around

It seems that the important part of calling `Category.load` is the call it makes to `Category.add_entry_mapping`. I can force this call to happen at load time, by:

1. Adding the call to each model class, and
2. using the `class_name` option with the associated class—the actual class, not a string containing its name—on my associations to force Rails to eagerly load the model classes.

The resulting code looks like this:

```ruby
class Requirement < ContentfulModel::Base
  self.content_type_id = "requirement"
  add_entry_mapping
  has_one :category, class_name: Category
end

class Category < ContentfulModel::Base
  self.content_type_id = "category"
  add_entry_mapping
  belongs_to_many :requirements, class_name: Requirement
end
```

**Comment by georgebrock** [comment]
It was pointed out by my colleagues that using `class_name: Category` to load the category model was a bit convoluted when I could just use a `require`. In the end, I went with this:

```ruby
require_relative "category"

class Requirement < ContentfulModel::Base
  self.content_type_id = "requirement"
  add_entry_mapping
  has_one :category
end
```

**Comment by dlitvakb** [comment]
Hey @georgebrock,

If you're using `contentful_rails` there's an optional eager loading mechanism in place that does this for you, if you're using `contentful_model` by itself, the eager loading has to be handled manually.

I will look into ways of having eager loading separate from the `Rails::Engine` implemented in `contentful_rails` and have it as part of `contentful_model` so that users of only this gem don't face weird eager loading mechanisms.

That said, we're about to release the 2.0.0 version of the Contentful SDK (it is currently going through the last round of code review), which will change the base Contentful::Entry to a more simplified (and better working) object, after that is done, I will re-write a big part of this library to take advantage of the new simplified objects. So please be a little patient until we get around this changes.

Cheers

**Comment by dlitvakb** [comment]
After re-writing most of  the library, I've changed my mind and think that the eager-loading mechanism belongs into the Rails::Engine as it's part of the Rails configuration pattern, while this gem can be integrated with applications that do not use Rails as their framework and would be overstepping it's boundaries.

The 2 above-mentioned methods (using `class_name: MyEntryKind` or requiring the file that contains the class) are both valid solutions to the issue. I personally prefer making the `class_name` explicit, but that's personal preference.

Cheers
